services:
  - type: web
    name: changi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PINECONE_API_KEY
        value: your_actual_key
      - key: OPENAI_API_KEY
        value: your_actual_key
      - key: OTHER_KEY
        value: other_value
